### ISSUE TITLE
Can't use ctrl + left mouse  click.

### ISSUE THREAD

**Issue by zkanda** [oblitum/caps2esc#10] opened 2017-07-06 16:31 UTC
Hello,

I can't seem to use the ctrl + left mouse click with the latest version. Basically I use it with my editor as a `go to definition` but it doesn't work normally. It's introduced in this commit: https://github.com/oblitum/caps2esc/commit/0266e4cc1e4e33973a6fe3b055e109c9f21ca76d

My skills on debugging this is beyond my capabilities so I can only report the issue for now.

Cheers!

**Comment by oblitum** [comment] 2017-07-06 16:51
I don't get the problem. The CTRL is a real one or CAPSLOCK turned CTRL?

**Comment by zkanda** [comment] 2017-07-09 15:48
@oblitum sorry for the late reply.

hmm let me try to elaborate:
For example, if you have an IDE say Eclipse or Intellij on a project, when you hover your mouse on a variable that is defined somewhere(e.g. on another file), you can long press CTRL + left click on the mouse, the effect is it would take you to where that variable is defined.

Trying this on the latest code doesn't seem to work.

If that is not enough, I could probably record my screen doing it. Please let me know and thank you so much for developing this project!

**Comment by oblitum** [comment] 2017-07-09 15:51
@zkanda you didn't answer my question: Is caps2esc affecting a real CTRL on your keyboard or the problem is with the CTRL from CAPSLOCK key that it provides?

**Comment by zkanda** [comment] 2017-07-09 16:28
@oblitum ops, sorry I misunderstood. caps2esc doesn't seem to affect the real CTRL and it works as expected, the problem is with CTRL from CAPSLOCK key that it provides.

**Comment by oblitum** [comment] 2017-07-10 17:29
OK, this is actually a duplicate of #5. If CTRL+MOUSE-EVENT was working for you before it was by accident. Closing as duplicate.

**Closed as completed by oblitum** 2017-07-10 17:29 UTC
